Split out common functions
Signed-off-by: Christopher Larson <kergoth@gmail.com>

diff --git a/rename-audio-by-album b/rename-audio-by-album
--- a/rename-audio-by-album
+++ b/rename-audio-by-album
@@ -1,5 +1,6 @@
 #!/bin/sh
 
+. "$(dirname "$0")/common-music.sh"
 . "$(dirname "$0")/trap.sh"
 
 case "$BASH_VERSION" in
@@ -19,52 +20,6 @@ set -e
 usage () {
     echo >&2 "${0##*/} [-n] SOURCE_DIR [SOURCE_DIR..]"
     exit 2
-}
-
-die () {
-    ret="$1"
-    shift
-    fmt="$1"
-    shift
-    printf >&2 "Error: $fmt\n" "$@"
-    exit $ret
-}
-
-get_metadata () {
-    fn="$1"
-    shift
-    pat="$(echo "$@" | sed -e 's/  */ /g')"
-    ffprobe -loglevel quiet -of compact=p=0 -show_entries format_tags "$fn" \
-        | tr '|' '\n' \
-        | sed -e 's/tag://' \
-        | grep -v '\\r' \
-        | while IFS="=" read -r key value; do
-            if [ -z "$key" ]; then
-                continue
-            fi
-            case "$key" in
-                *\ *)
-                    key="$(echo "$key" | tr " " _)"
-                    ;;
-            esac
-            key="$(printf '%s\n' "$key" | tr ".:/-#=\`" "_______" | tr "[:upper:]" "[:lower:]" | tr -d '\')"
-            case " $pat " in
-                *\ $key\ *)
-                    ;;
-                *)
-                    continue
-                    ;;
-            esac
-            value="$(printf '%s\n' "$value" | sed -e 's/"/\\"/g; s/\\$//; s/`/\\`/g')"
-            printf '%s="%s"\n' "$key" "$value"
-        done
-}
-
-eval_metadata () {
-    # get_metadata "$@" | while read -r line; do
-    #     ( eval "$line" ) >/dev/null 2>&1 || die 1 'Unable to eval `%s`' "$line"
-    # done
-    eval "$(get_metadata "$@")"
 }
 
 get_tracknumber () {
@@ -117,15 +72,12 @@ get_discnumber () {
     printf '\n'
 }
 
-md_vars="track tracknumber tracktotal totaltracks \
-         disc discnumber disctotal totaldiscs \
-         artist album_artist title album compilation"
 get_new_filename () {
     fn="$1"
     source_dir="$2"
     compilation=
     (
-        eval_metadata "$fn" $md_vars || die "Failed to eval metadata for $fn"
+        eval_common_metadata "$fn" || die 1 "Failed to eval metadata for $fn"
 
         oldtracktotal="$tracktotal"
         track="$(get_tracknumber || :)"
