rename-audio-by-album: skip filenames without useful tags
Signed-off-by: Christopher Larson <kergoth@gmail.com>

diff --git a/rename-audio-by-album b/rename-audio-by-album
--- a/rename-audio-by-album
+++ b/rename-audio-by-album
@@ -76,6 +76,10 @@ for source_dir; do
         clearbar
         progressbar "$curcount" "$filecount" "${source_dir##*/}" "$curcount/$filecount    "
         eval_common_metadata "$fn"
+        if [ -z "$artist" ] && [ -z "$title" ] && [ -z "$tracknumber" ]; then
+            echo >&2 "Error: no useful tags for $fn, skipping"
+            continue
+        fi
         newfn="$(get_new_filename ${separate_discs+-d} "$fn" "$source_dir")"
         if [ $(echo "$newfn" | wc -l) -ne 1 ]; then
             echo >&2 "Error: invalid new fn $newfn for $fn, skipping"
