rename-audio-by-album: skip filenames with newlines
Signed-off-by: Christopher Larson <kergoth@gmail.com>

diff --git a/rename-audio-by-album b/rename-audio-by-album
--- a/rename-audio-by-album
+++ b/rename-audio-by-album
@@ -97,6 +97,10 @@ for source_dir; do
         curcount=$((curcount + 1))
         progressbar $curcount "$filecount" "${source_dir##*/}" "$curcount/$filecount    "
         newfn="$(get_new_filename ${separate_discs+-d} "$fn" "$source_dir")"
+        if [ $(echo "$newfn" | wc -l) -ne 1 ]; then
+            echo >&2 "Error: invalid new fn $newfn for $fn, skipping"
+            continue
+        fi
         if [ -z "$newfn" ]; then
             echo >&2 "Error: unable to determine new filename for $fn, skipping"
             continue
