split-singles: numerous changes. flatten, add individual arg, hoist samples, etc
Signed-off-by: Christopher Larson <kergoth@gmail.com>

diff --git a/split-singles b/split-singles
--- a/split-singles
+++ b/split-singles
@@ -4,180 +4,52 @@
 
 investigate_threshold=1
 destdir=.
-albumsdir=./_Albums
-extrasdir="./_Albums With Extra Tracks"
-incompletedir="./_Incomplete Albums"
-singlesdir=./_Singles
-singletracksdir="./_Single Tracks"
-samplersdir="./_Samplers"
+prefix=
+albumsdir=${prefix}Albums
+extrasdir="${prefix}Albums With Extra Tracks"
+incompletedir="${prefix}Incomplete Albums"
+singlesdir=${prefix}Singles
+singletracksdir="${prefix}Single Tracks"
+samplersdir="${prefix}Samplers"
 # Genres that get their own toplevel directories to ease navigation
 # Game and Soundtrack also get flattened, as I rarely browse them by artist
-hoistedgenresdir="./_%s Albums"
-hoisted_genres="Game|Soundtrack|Christmas"
+hoistedgenresdir="${prefix}%s Albums"
+hoisted_genres="Game|Soundtrack|Christmas|Classical"
+flattened_genres="Game|Soundtrack"
+flattened_dirs="$samplersdir"
 
 # Games with data tracks and amazon albums whose videos and booklets are
 # counted in the track total. This blacklist only allows one track to be
 # missing at this time.
-incomplete_blacklist="Descent|Shadow Warrior|Fantasy General|Stargunner Original Soundtrack|King's Quest VI Heir Today, Gone Tomorrow|Command & Conquer： Red Alert： Counterstrike|Command & Conquer： Tiberian Dawn： Covert Operations|Warcraft II： Tides of Darkness|Total Annihilation|Moto Racer|Return to Zork|Quake|Hexen II|.*\\[\\+video\\]|.*\\[\\+Digital Booklet\\]"
+incomplete_blacklist="Descent Mac Game Soundtrack|Shadow Warrior|Fantasy General|Stargunner Original Soundtrack|King's Quest VI Heir Today, Gone Tomorrow|Command & Conquer： Red Alert： Counterstrike|Command & Conquer： Tiberian Dawn： Covert Operations|Warcraft II： Tides of Darkness|Total Annihilation|Moto Racer|Return to Zork|Quake|Hexen II|.*\\[\\+video\\]|.*\\[\\+Digital Booklet\\]"
 
 if which gln >/dev/null 2>&1; then
-    alias link='gln -rsfv'
+    alias link='gln -rsf'
 else
-    alias link='ln -rsfv'
+    alias link='ln -rsf'
 fi
+
+usage() {
+    echo >&2 "${0##*/} [-r RELATIVETO] PATH [PATH..]"
+    exit 2
+}
+
+individual=0
+while getopts i:h opt; do
+    case "$opt" in
+        i)
+            individual=1
+            ;;
+        \? | h)
+            usage
+            ;;
+    esac
+done
+shift $((OPTIND - 1))
 
 if [ $# -eq 0 ]; then
     set -- .
 fi
-
-get_tracknumber() {
-    case "$track" in
-        */*)
-            tracknumber="${track%/*}"
-            tracktotal="${track##*/}"
-            ;;
-        '') ;;
-
-        *)
-            tracknumber="$track"
-            ;;
-    esac
-    if [ -z "$tracknumber" ]; then
-        return 1
-    fi
-    if [ -z "$tracktotal" ] && [ -n "$totaltracks" ]; then
-        tracktotal="$totaltracks"
-    fi
-    printf "$tracknumber"
-    if [ -n "$tracktotal" ]; then
-        printf "/$tracktotal"
-    fi
-    printf '\n'
-}
-
-get_discnumber() {
-    case "$disc" in
-        */*)
-            discnumber="${disc%/*}"
-            disctotal="${disc##*/}"
-            ;;
-        '') ;;
-
-        *)
-            discnumber="$disc"
-            ;;
-    esac
-    if [ -z "$discnumber" ]; then
-        discnumber=1
-    fi
-    if [ -z "$disctotal" ] && [ -n "$totaldiscs" ]; then
-        disctotal="$totaldiscs"
-    fi
-    printf "$discnumber"
-    if [ -n "$disctotal" ]; then
-        printf "/$disctotal"
-    fi
-    printf '\n'
-}
-
-# We need to get the total tracks for all discs to get a true total
-get_album_track_total() {
-    file_count=$(find "$1/" -not -name ._\* \( -iname \*.flac -o -iname \*mp3 -o -iname \*.m4a -o -iname \*.ogg -o -iname \*.dsf \) | wc -l)
-    find "$1/" -not -name ._\* \( -iname \*.flac -o -iname \*mp3 -o -iname \*.m4a -o -iname \*.ogg -o -iname \*.dsf \) \
-        | (
-            total=0
-            while read -r fn; do
-                eval_common_metadata "$fn"
-
-                track="$(get_tracknumber)"
-                case "$track" in
-                    */*)
-                        tracknumber="${track%/*}"
-                        tracktotal="${track##*/}"
-                        ;;
-                    *)
-                        tracknumber="$track"
-                        tracktotal=
-                        ;;
-                esac
-
-                disc="$(get_discnumber)"
-                case "$disc" in
-                    */*)
-                        discnumber="${disc%/*}"
-                        disctotal="${disc##*/}"
-                        ;;
-                    *)
-                        discnumber="$disc"
-                        disctotal=1
-                        ;;
-                esac
-
-                existing_total="$(eval "printf '%s' \"\${total$discnumber}\"")"
-                if [ -z "$existing_total" ]; then
-                    if [ -n "$tracktotal" ]; then
-                        eval "total$discnumber=$tracktotal"
-                        total=$((total + tracktotal))
-                    else
-                        return 0
-                    fi
-                fi
-                if [ $total -ge $file_count ]; then
-                    break
-                fi
-            done
-            if [ $total -gt 0 ]; then
-                echo "$total"
-            fi
-        )
-}
-
-get_genre() {
-    eval_common_metadata "$1" genre albumgenre
-    if [ -n "$albumgenre" ]; then
-        genre="$albumgenre"
-    elif [ -z "$genre" ]; then
-        # shellcheck disable=SC2016
-        genre="$(exiftool -qm -AlbumGenre -p '$AlbumGenre' "$1" 2>/dev/null | xargs)"
-        if [ -z "$genre" ]; then
-            # shellcheck disable=SC2016
-            genre="$(exiftool -qm -Genre -p '$Genre' "$1" 2>/dev/null | xargs)"
-        fi
-    fi
-
-    # Sanitize / Improve consistency. Better plan: fix the tags
-    case "$genre" in
-        None|''|Miscellaneous|Other|Unclassifiable|hSH)
-            genre=
-            ;;
-        Soundtracks)
-            genre=Soundtrack
-            ;;
-        Videogame|Video\ Game*)
-            genre=Game
-            ;;
-        Dance\ \&\ DJ)
-            genre=Dance
-            ;;
-        Heavy\ Metal)
-            genre=Metal
-            ;;
-        Holiday)
-            genre=Christmas
-            ;;
-    esac
-    if [ "$genre" != Game ]; then
-        if [ "$releasetype" = soundtrack ] \
-            || basename "$dir" | grep -qi soundtrack \
-            || basename "$dir" | grep -qiw ost; then
-            genre=Soundtrack
-        fi
-    fi
-    if [ -z "$genre" ]; then
-        genre=Unknown\ Genre
-    fi
-    echo "$genre"
-}
 
 for source_dir; do
     if [ "$(cd "$source_dir" && pwd -P)" = "$(pwd -P)" ]; then
@@ -189,12 +61,17 @@ for source_dir; do
             continue
         fi
         dir="${dir%/}"
+        base="${dir##*/}"
         count="$(find "$dir/" -not -name ._\* \( -iname \*.flac -o -iname \*mp3 -o -iname \*.m4a -o -iname \*.ogg -o -iname \*.dsf \) | wc -l)"
         if [ $count -lt 1 ]; then
             continue
         fi
         first="$(find "$dir/" -not -name ._\* \( -iname \*.flac -o -iname \*mp3 -o -iname \*.m4a -o -iname \*.ogg -o -iname \*.dsf \) | head -n 1)"
         total="$(get_album_track_total "$dir/")"
+
+        genre= albumgenre= releasetype=
+        eval_common_metadata "$first" genre albumgenre releasetype
+        genre="$(get_genre "$first")"
 
         if [ -z "$total" ]; then
             if [ $count -gt 1 ]; then
@@ -203,7 +80,8 @@ for source_dir; do
                 d="$singletracksdir"
             fi
         elif [ $count -eq $total ]; then
-            if [ $total -eq 1 ] || basename "$dir" | grep -q Single; then
+            if echo "$releasetype" | tr ',' ' ' | grep -qwi single \
+                || [ $total -eq 1 ] || echo "$base" | grep -q Single; then
                 d="$singlesdir"
             else
                 d="$albumsdir"
@@ -213,10 +91,13 @@ for source_dir; do
             # find "$dir/" -not -name ._\* \( -iname \*.flac -o -iname \*mp3 -o -iname \*.m4a -o -iname \*.ogg \)
             d="$extrasdir"
         elif [ $total -eq 1 ]; then
+            # Shouldn't be possible to get here
+            echo >&2 "Error: total is 1, but count is less than 1"
+            exit 1
             d="$singletracksdir"
         else
             if [ $count -gt "$investigate_threshold" ]; then
-                if [ $count -eq $((total - 1)) ] && basename "$dir" | grep -qEx "$incomplete_blacklist"; then
+                if [ $count -eq $((total - 1)) ] && echo "$base" | grep -qEx "$incomplete_blacklist"; then
                     d="$albumsdir"
                 else
                     # Possibly screwed up, or an incomplete album
@@ -227,46 +108,81 @@ for source_dir; do
             fi
         fi
 
-        # Special case
-        if echo "$base" | grep -wi sampler; then
-            d="$samplersdir"
-        fi
-
+        rel="$(relpath "$dir" "$source_dir")"
+        echo "$rel: $count / $total"
         if [ "$d" = "$singletracksdir" ]; then
-            mkdir -p "$d"
+            dest="$d"
+            mkdir -p "$dest"
             find "$dir/" -not -name ._\* \( -iname \*.flac -o -iname \*mp3 -o -iname \*.m4a -o -iname \*.ogg \) \
                 | while read -r fn; do
                     ext="${fn##*.}"
-                    link "$fn" "$d/$(exiftool -qm -Artist -Title -p '$Artist - $Title' "$fn" 2>/dev/null).$ext"
+                    (
+                        artist= title=
+                        eval_common_metadata "$fn" artist title
+                        if [ -z "$artist" ]; then
+                            artist="[unknown]"
+                        fi
+                        newfn="$(echo "$artist - $title.$ext" | tr ':/' '∶／' | sed -e 's/^\.//')"
+                        if [ -e "$dest/$newfn" ]; then
+                            echo >&2 "Error: $dest/$newfn already exists, can't link from $dir"
+                            continue
+                        fi
+                        link "$fn" "$dest/$newfn"
+                    )
                 done
         else
-            rel="$(relpath "$dir" "$source_dir")"
-            dest="$d/$rel"
-            if [ -n "$hoisted_genres" ]; then
-                genre="$(get_genre "$first")"
-                if echo "$genre" | grep -Eqx "$hoisted_genres"; then
+            dest=
+            if [ -n "$hoisted_genres" ] || [ -n "$flattened_genres" ]; then
+                if [ -n "$hoisted_genres" ] \
+                    && echo "$genre" | grep -Eqx "$hoisted_genres"; then
                     d="$(printf "$hoistedgenresdir" "$genre")"
-                    dest="$d/$(basename "$rel")"
+                fi
+                if [ -n "$flattened_genres" ] \
+                    && echo "$genre" | grep -Eqx "$flattened_genres"; then
+                    dest="$d/$base"
                 fi
             fi
 
-            destdir="$(dirname "$dest")"
-            echo "$rel: $count / $total"
-            mkdir -p "$destdir"
-            if [ -h "$dest" ]; then
+            if echo "$base" | grep -wi sampler; then
+                d="$samplersdir"
+            fi
+
+            if echo "$d" | grep -Eqx "$flattened_dirs"; then
+                dest="$d/$base"
+            elif [ -z "$dest" ]; then
+                dest="$d/$rel"
+            fi
+            dest="$destdir/$dest"
+
+            if [ $individual -eq 1 ]; then
                 if [ -d "$dest" ]; then
-                    olddest="$(cd "$dest" && pwd -P)"
-                else
-                    olddest="$(cd "$destdir" && abspath "$(readlink "$(basename "$rel")")")"
-                fi
-                absdir="$(cd "$dir" && pwd -P)"
-                if [ "$olddest" != "$absdir" ]; then
-                    echo >&2 "Error: $dest exists but points to $olddest, not $absdir"
+                    echo >&2 "Error: $dest already exists, can't link from $dir"
                     continue
                 fi
+                mkdir -p "$dest"
+                find "$dir/" -not -name ._\* \( -iname \*.flac -o -iname \*mp3 -o -iname \*.m4a -o -iname \*.ogg \) \
+                    | while read -r fn; do
+                        link "$fn" "$dest/"
+                    done
+            else
+                dest_parent="$(dirname "$dest")"
+                mkdir -p "$dest_parent"
+                if [ -h "$dest" ]; then
+                    if [ -d "$dest" ]; then
+                        olddest="$(cd "$dest" && pwd -P)"
+                    else
+                        olddest="$(cd "$dest_parent" && abspath "$(readlink "$base")")"
+                    fi
+                    absdir="$(cd "$dir" && pwd -P)"
+                    if [ "$olddest" != "$absdir" ]; then
+                        echo >&2 "Error: $dest exists but points to $olddest, not $absdir"
+                        continue
+                    fi
+                fi
+                rm -f "$dest"
+                link "$dir" "$dest"
             fi
-            rm -f "$dest"
-            link "$dir" "$dest"
+
         fi
     done
 done
